server:
  servlet:
    context-path: /explore
  error:
    include-message: NEVER
    include-binding-errors: NEVER
    include-stacktrace: NEVER
    include-exception: false

spring:
  security:
    user:
      name: admin
      password: password
  h2:
    console:
      enabled: true
    # console:
    #   path: /h2-console
    #   settings.trace: false
    #   settings.web-allow-others: false
  datasource:
    # url: jdbc:h2:mem:testdb
    url: jdbc:h2:mem:mydb;NON_KEYWORDS=USER
    # url: dbc:h2:file:/data/sampledata  
    driverClassName: org.h2.Driver
    username: admin
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    # defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
